stages:
  cleaning:
    cmd: |
      poetry run python -m src.data.load --i data/raw/power_tetouan_city_modified.csv --s data/interim/power_tetouan_city_loaded.csv
      poetry run python -m src.data.clean --input data/interim/power_tetouan_city_loaded.csv --o data/interim/power_tetouan_city_modified_clean.csv 
    deps:
      - src/data/load.py
      - src/data/clean.py
      - data/raw/power_tetouan_city_modified.csv
    outs:
      - data/interim/power_tetouan_city_modified_clean.csv

  preprocess:
    cmd: |
      poetry run python -m scripts.preprocess_n_save --input data/interim/power_tetouan_city_modified_clean.csv  --output data/processed/scaled.csv
    deps:
      - scripts/preprocess_n_save.py
      - src/features/preprocessing.py
      - data/interim/power_tetouan_city_modified_clean.csv
    outs:
      - data/processed/scaled.csv

  modeling:
    cmd: |
      poetry run python -m scripts.run_modeling --input data/processed/scaled.csv --output_dir models
    deps:
      - scripts/run_modeling.py
      - src/models/modeling.py
      - data/processed/scaled.csv
    outs:
      - models