stages:
  cleaning:
    cmd: >
      poetry run python -m mlops_power_tetouan.pipelines.run_cleaning
      --input data/raw/power_tetouan_city_modified.csv
      --output data/interim/power_tetouan_city_modified_clean.csv
    deps:
      - mlops_power_tetouan/pipelines/run_cleaning.py
      - mlops_power_tetouan/dataset.py
      - mlops_power_tetouan/features/cleaning.py
      - data/raw/power_tetouan_city_modified.csv
    outs:
      - data/interim/power_tetouan_city_modified_clean.csv

  preprocess:
    cmd: >
      poetry run python -m mlops_power_tetouan.pipelines.preprocess_n_save
    deps:
      - mlops_power_tetouan/pipelines/preprocess_n_save.py
      - mlops_power_tetouan/features.py
      - data/interim/power_tetouan_city_modified_clean.csv
    outs:
      - data/processed/scaled.csv

  modeling:
    cmd: >
      poetry run python -m mlops_power_tetouan.pipelines.run_modeling
    deps:
      - mlops_power_tetouan/pipelines/run_modeling.py
      - mlops_power_tetouan/modeling/modeling.py
      - data/processed/scaled.csv
    outs:
      - models